### ISSUE TITLE
SMTP-Header with linebreak ist not parsed correct

### ISSUE THREAD

**Issue by acbekoac** [z0m31en7/WhatMail#1]
I used ctrl-u to view the SMTP header in Thunderbird and copy these into a text file. Here some had a line break, for example

Received: from srvpsmail0.psrato.pt ([fe80::cd08:f794:f374:3943]) by
 srvpsmail0.psrato.pt ([fe80::cd08:f794:f374:3943%3]) with mapi id
 15.01.2507.023; Mon, 22 May 2023 10:36:16 +0100

Those are not parsed complete/correct

**Comment by z0m31en7** [comment]
If the email header lines in your text file contain line breaks, the parsing might not work correctly. To handle multiline headers, we can modify the code to concatenate the lines until a new header field starts, Let me update the code.

**Comment by z0m31en7** [comment]
The issue is fixed, thanks for contributing.
